#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Integrate temp_routes/group*.json into client/src/data/travelRoutes.ts.
The generated module exports strongly typed route data plus helper functions.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "client" / "src" / "data" / "travelRoutes.ts"

TS_HEADER = """// Auto-generated by scripts/integrate_travel_routes.py
// Do not edit manually; regenerate instead.

export interface RouteStop {
  time: string;
  title: string;
  type: string;
  desc: string;
  img: string;
  tips?: string;
}

export interface PracticalInfo {
  transport: string;
  accommodation: string;
  food: string;
  bestTime: string;
  tips: string[];
  budget: string;
}

export interface RoutePlan {
  title: string;
  subtitle: string;
  duration: string;
  stops: RouteStop[];
  practicalInfo: PracticalInfo;
}

export interface CityRoute {
  id: string;
  name: string;
  caseName: string;
  country: string;
  description: string;
  themes: Record<string, RoutePlan[]>;
}

export type DurationKey = "1day" | "2days" | "3days";

export const DURATIONS: { value: DurationKey; label: string }[] = [
  { value: "1day", label: "1日（紧凑）" },
  { value: "2days", label: "2日（深度）" },
  { value: "3days", label: "3日+（全景）" },
];
"""

TS_FOOTER = """
export const CITY_OPTIONS = Object.values(TRAVEL_ROUTES).map((city) => ({
  value: city.id,
  label: `${city.name} · ${city.caseName}`,
}));

export function getRoute(
  cityId: string,
  theme: string,
  duration: DurationKey
): RoutePlan | null {
  const city = TRAVEL_ROUTES[cityId];
  if (!city) return null;
  const plans = city.themes[theme];
  if (!plans) return null;
  const index = duration === "1day" ? 0 : duration === "2days" ? 1 : 2;
  return plans[index] ?? null;
}

export function getFirstAvailableRoute(cityId: string): RoutePlan | null {
  const city = TRAVEL_ROUTES[cityId];
  if (!city) return null;
  for (const plans of Object.values(city.themes)) {
    if (plans.length > 0) return plans[0];
  }
  return null;
}
"""


def normalize_duration_order(themes: dict) -> dict:
    """Ensure each theme's plans are ordered 1day, 2days, 3days."""
    result = {}
    for theme_key, theme in themes.items():
        plans = []
        for dur in ["1day", "2days", "3days"]:
            if dur in theme:
                plan = dict(theme[dur])
                # Guarantee the stops list exists and is a list
                plan.setdefault("stops", [])
                plan.setdefault("practicalInfo", {
                    "transport": "",
                    "accommodation": "",
                    "food": "",
                    "bestTime": "",
                    "tips": [],
                    "budget": "",
                })
                plans.append(plan)
        result[theme_key] = plans
    return result


def main() -> None:
    routes_dir = ROOT / "temp_routes"
    merged = {}
    for i in range(1, 6):
        path = routes_dir / f"group{i}.json"
        if not path.exists():
            print(f"Warning: {path} not found, skipping.")
            continue
        with path.open(encoding="utf-8") as f:
            group = json.load(f)
        for key, value in group.items():
            if key.startswith("_"):
                continue
            if key in merged:
                print(f"Warning: duplicate city {key}; overwriting with group {i}.")
            merged[key] = {
                "id": key,
                "name": value.get("name", key),
                "caseName": value.get("case", ""),
                "country": value.get("country", ""),
                "description": value.get("description", ""),
                "themes": normalize_duration_order(value.get("themes", {})),
            }

    # Stable order for deterministic output
    ordered = {k: merged[k] for k in sorted(merged.keys())}

    body = "export const TRAVEL_ROUTES: Record<string, CityRoute> = "
    body += json.dumps(ordered, ensure_ascii=False, indent=2)
    body += ";"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TS_HEADER + "\n" + body + TS_FOOTER, encoding="utf-8")
    print(f"Wrote {OUT} with {len(ordered)} cities.")


if __name__ == "__main__":
    main()
